#!/bin/sh

vol="$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"

# If muted, print "  MUTED" and exit.
[ "$vol" != "${vol%\[MUTED\]}" ] && echo "  MUTED" && exit

vol="${vol#Volume: }"

split() {
	# For ommiting the . without calling and external program.
	IFS=$2
	set -- $1
	printf '%s' "$@"
}

printf "  %.0f%%" "$(split "$vol" ".")"
