#!/bin/sh

if [ "$(cat /sys/class/net/w*/operstate 2>/dev/null)" = 'up' ] ; then
    echo "   $(iwgetid -r)"
elif [ "$(cat /sys/class/net/w*/operstate 2>/dev/null)" = 'down' ] ; then
	[ "$(cat /sys/class/net/w*/flags 2>/dev/null)" = '0x1003' ] && echo " 󱛅 UNCONNECTED" || echo " 󱛅 OFF"
fi
