#!/bin/sh

for battery in /sys/class/power_supply/BAT?*; do
    # If non-first battery, print separator.
	[ -n "${capacity+x}" ] && printf " | "

    battery_name="${battery##*/}"
	capacity="$(cat "$battery/capacity" 2>&1)"

    case "$(cat "$battery/status" 2>&1)" in
		"Full")         status="o" ;;
		"Discharging")  status="-" ;;
		"Charging")     status="+" ;;
		"Not charging") status="o" ;;
		"Unknown")      status="?" ;;
		*) exit 1 ;;
	esac

    printf "%s: %d%%%s" "$battery_name" "$capacity" "$status"
done
